name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Triggers the workflow when pushing to the main branch
  pull_request:
    branches:
      - main  # Optionally, also run the workflow on pull requests

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64,linux/arm64/v8
        push: true
        tags: podpalch/ha-devi-mqtt:latest

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
